volumes:
  db:
version: "3"
name: harmony
services:
  db:
    container_name: db
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    volumes:
      - db:/var/lib/postgresql/data