import type { Metadata } from 'next'
import './globals.css'
import {HarmonySetup} from '../packages/editor/src/index';
import { ClerkProvider } from '@clerk/nextjs'
import { TrpcProvider } from '../utils/trpc-provider'
import {fonts, mulish} from '@harmony/util/src/fonts';



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
		<ClerkProvider>
			<TrpcProvider>
				<html className="hw-h-full hw-bg-white" lang="en">
					<body className={`${mulish.className} hw-h-full hw-bg-white`}>
						{children}
						{process.env.ENV === 'production' ? <HarmonySetup repositoryId="da286f25-b5de-4003-94ed-2944162271ed" fonts={fonts}/> : <HarmonySetup repositoryId='fbefdac4-8370-4d6d-b440-0307882f0102' local fonts={fonts}/> }
							{/* <Script id="harmony-tag" src="bundle.js"></Script>
							<Script>
							{`(function() {
								const script = document.getElementById('harmony-tag');
								script.addEventListener('load', function() {
									window.HarmonyProvider({repositoryId:'clrf5dxjg000169tj4bwcrjj0'});
								});
								})()`}
							</Script> */}
					</body>
				</html>
			</TrpcProvider>
		</ClerkProvider>
  )
}
