[package]
authors = ["Braydon Jones <braydon.jones28@gmail.com>"]
description = "SWC plugin for harmony.ai"
edition = "2021"
license = "Apache-2.0"
name = "harmony-plugin"
publish = false
version = "0.4.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
once_cell = "1.8.0"
regex = "1.5"
serde = "1"
serde_json = "1"
swc_common = { version = "0.33.12", features = ["concurrent"] }
tracing = { version = "0.1.37", features = ["release_max_level_off"] }
swc_core = { version = "0.87.3", features = ["common", "ecma_utils", "ecma_plugin_transform"] }
swc_ecma_ast = "0.110.15"
swc_ecma_utils = "0.125.0"
swc_ecma_visit = "0.96.15"
swc_plugin_macro = "0.9.15"
base64 = "0.21.7"
pathdiff = "0.1.0"
fancy-regex = "0.13.0"
console_error_panic_hook = "0.1.7"
path-slash = "0.2.1"

[dev-dependencies]
