import type { Metadata } from 'next'
import './globals.css'
import { inter } from '@harmony/util/src/fonts'
import { Footer } from '../components/footer'
import { Navbar } from './components/navbar'
import { DarkmodeHTML } from './components/dark-mode-toggle'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <DarkmodeHTML>
      <head>
        <link
          rel='stylesheet'
          href='https://api.fontshare.com/css?f%5B%5D=switzer@400,500,600,700&amp;display=swap'
        />
        <link
          rel='alternate'
          type='application/rss+xml'
          title='The Radiant Blog'
          href='/blog/feed.xml'
        />
      </head>
      <body
        className={`hw-min-h-screen hw-bg-background hw-font-sans hw-antialiased ${inter.className}`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </DarkmodeHTML>
  )
}
