import type { Metadata } from 'next'
import './globals.css'
import { inter } from '@harmony/util/src/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`hw-min-h-screen hw-bg-background hw-font-sans hw-antialiased ${inter.className}`}
      >
        {children}
      </body>
    </html>
  )
}
