import type { BuildContext, ChangeRecord } from './types'

interface GroupedChange {
  file: string
  line: number
  elementName?: string
  changes: ChangeRecord[]
}

export function formatPRD(context: BuildContext): string {
  const sections: string[] = []

  // Header
  sections.push('# Code Changes Context\n')

  // Summary
  sections.push('## Summary\n')
  sections.push(`- Total changes: ${context.metadata.totalChanges}`)
  sections.push(`- Concrete changes: ${context.metadata.concreteChanges}`)
  sections.push(`- Uncertain changes: ${context.metadata.uncertainChanges}`)
  sections.push(`- Affected files: ${context.affectedFiles.size}\n`)

  // Group changes by file
  const changesByFile = groupChangesByFile(context.changes)

  sections.push('## Changes by File\n')

  for (const [file, changes] of Array.from(changesByFile.entries())) {
    sections.push(`### ${file}\n`)

    // Group by element/line within each file
    const groupedChanges = groupChangesByElement(changes)

    // Separate concrete and uncertain changes
    const concreteGroups = groupedChanges.filter((g) =>
      g.changes.some((c) => c.confidence === 'concrete'),
    )
    const uncertainGroups = groupedChanges.filter(
      (g) =>
        g.changes.every((c) => c.confidence === 'uncertain') &&
        !concreteGroups.includes(g),
    )

    // Format concrete changes
    if (concreteGroups.length > 0) {
      sections.push('#### Concrete Changes')
      sections.push(
        'These changes have exact locations and values. You should implement these as specified:\n',
      )

      let changeNumber = 1
      for (const group of concreteGroups) {
        const concreteChanges = group.changes.filter(
          (c) => c.confidence === 'concrete',
        )

        sections.push(
          `${changeNumber}. **Line ${group.line}**: ${formatChangeDescription(concreteChanges)}`,
        )

        // Show properties being changed
        for (const change of concreteChanges) {
          if (change.change.propertyName) {
            sections.push(`   - Property: \`${change.change.propertyName}\``)
          }
          if (change.change.oldValue) {
            sections.push(`   - Old value: \`${change.change.oldValue}\``)
          }
          if (change.change.newValue) {
            sections.push(`   - New value: \`${change.change.newValue}\``)
          }
        }

        // Show code snippet
        const codeSnippet = concreteChanges.find((c) => c.change.codeSnippet)
          ?.change.codeSnippet
        if (codeSnippet) {
          sections.push('   - Code snippet:')
          sections.push('     ```tsx')
          sections.push(`     ${codeSnippet}`)
          sections.push('     ```')
        }

        // Show implementation guidance
        const implementationGuidance =
          generateImplementationGuidance(concreteChanges)
        if (implementationGuidance) {
          sections.push(`   - Implementation: ${implementationGuidance}`)
        }

        sections.push('')
        changeNumber++
      }
    }

    // Format uncertain changes
    if (uncertainGroups.length > 0) {
      sections.push('#### Uncertain Changes')
      sections.push(
        'These changes require your judgment on how to implement:\n',
      )

      let changeNumber = 1
      for (const group of uncertainGroups) {
        for (const change of group.changes) {
          sections.push(
            `${changeNumber}. **Line ${group.line}**: ${change.change.description}`,
          )
          sections.push(
            `   - Reason: Unable to determine exact implementation location`,
          )
          sections.push(
            `   - Suggestion: Review the code and implement the change appropriately`,
          )
          sections.push('')
          changeNumber++
        }
      }
    }

    sections.push('')
  }

  // Add footer
  sections.push('---')
  sections.push(
    '\n*This PRD was generated by Harmony Publisher in build-context mode.*',
  )

  return sections.join('\n')
}

function groupChangesByFile(
  changes: ChangeRecord[],
): Map<string, ChangeRecord[]> {
  const grouped = new Map<string, ChangeRecord[]>()

  for (const change of changes) {
    const file = change.location.file
    if (!grouped.has(file)) {
      grouped.set(file, [])
    }
    grouped.get(file)!.push(change)
  }

  // Sort files alphabetically
  return new Map(
    [...Array.from(grouped.entries())].sort((a, b) => a[0].localeCompare(b[0])),
  )
}

function groupChangesByElement(changes: ChangeRecord[]): GroupedChange[] {
  const grouped = new Map<string, GroupedChange>()

  for (const change of changes) {
    // Group by line number (changes to same element)
    const key = `${change.location.line}`

    if (!grouped.has(key)) {
      grouped.set(key, {
        file: change.location.file,
        line: change.location.line,
        elementName: change.location.elementName,
        changes: [],
      })
    }

    grouped.get(key)!.changes.push(change)
  }

  // Sort by line number
  return [...Array.from(grouped.values())].sort((a, b) => a.line - b.line)
}

function formatChangeDescription(changes: ChangeRecord[]): string {
  if (changes.length === 1) {
    return changes[0].change.description
  }

  // Multiple changes to same element
  const descriptions = changes.map((c) => c.change.description)
  return `Multiple changes: ${descriptions.join('; ')}`
}

function generateImplementationGuidance(changes: ChangeRecord[]): string {
  const guidance: string[] = []

  for (const change of changes) {
    if (change.changeType === 'literal') {
      if (change.change.oldValue && change.change.newValue) {
        guidance.push(
          `Replace "${change.change.oldValue}" with "${change.change.newValue}"`,
        )
      }
    } else if (change.changeType === 'attribute') {
      if (change.change.propertyName) {
        if (change.change.oldValue) {
          guidance.push(
            `Update ${change.change.propertyName} from "${change.change.oldValue}" to "${change.change.newValue}"`,
          )
        } else {
          guidance.push(
            `Add ${change.change.propertyName}="${change.change.newValue}"`,
          )
        }
      }
    } else if (change.changeType === 'style') {
      guidance.push(
        `Add style property ${change.change.propertyName}: "${change.change.newValue}"`,
      )
    } else if (change.changeType === 'element-create') {
      guidance.push('Insert new element at this location')
    } else if (change.changeType === 'element-delete') {
      guidance.push('Remove this element')
    }
  }

  return guidance.join('; ')
}
